executable = /usr/bin/bash
arguments = /fast/mkaut/ma-thesis/confs/encode/rid/jobs/encode.sh
error = /fast/mkaut/ma-thesis/confs/encode/rid/jobs/encode2.$(Process).err
output = /fast/mkaut/ma-thesis/confs/encode/rid/jobs/encode2.$(Process).out
log = /fast/mkaut/ma-thesis/confs/encode/rid/jobs/encode2.$(Process).log
request_memory = 40000
requirements = TARGET.CUDAGlobalMemoryMb > 40000
request_disk = 10G
request_cpus = 1
request_gpus = 1
queue
